### ISSUE TITLE
Possible intermittent Internet ipv4 connectivity issues in osic-cloud1

### ISSUE THREAD

**Issue by cboylan** [osic/osic-clouds#6] opened 2016-10-11 22:32 UTC
OpenStack Infra tests have run into connection errors to https://github.com which does not have an ipv6 AAAA record so all communication to there from the openstack infra tenant will be through the ipv4 NAT to the Internet.

Running `while git clone https://github.com/puppetlabs/puppetlabs-apache/ ; do rm -rf puppetlabs-apache ; done` in a loop usually succeeds but I have received `fatal: unable to access 'https://github.com/puppetlabs/puppetlabs-apache/': GnuTLS recv error (-54): Error in the pull function.` and `fatal: unable to access 'https://github.com/puppetlabs/puppetlabs-apache/': gnutls_handshake() failed: Error in the pull function.` after several attempts. The instance uuid for the host that hit this is `1340b11a-7b69-4b89-bd24-2daa53598e0c` with ipv6 addr `2001:4800:1ae1:18:f816:3eff:fed2:7c64` and ipv4 addr `10.1.29.54`.

Could be that the NAT is failing or that github is telling us to go away or something in between.

**Comment by cboylan** [comment] 2016-10-11 22:33
http://logs.openstack.org/58/377158/13/check/gate-puppet-openstack-integration-4-scenario001-tempest-centos-7/f727ce2/console.html#_2016-10-11_21_28_36_501180 is a link to the zuul side failure.

**Comment by cboylan** [comment] 2016-10-11 22:43
Looking at other jobs that failed it doesn't look like this is limited to Github implying it may be a more localized issue.

http://logs.openstack.org/58/377158/13/check/gate-puppet-openstack-integration-4-scenario001-tempest-ubuntu-xenial/b9c92f3/console.html#_2016-10-11_21_24_44_018219 is connection issues to ceph apt repository and http://logs.openstack.org/58/377158/13/check/gate-puppet-openstack-integration-4-scenario002-tempest-centos-7/494703d/console.html#_2016-10-11_21_32_40_033697 is connection issues to a yum repository.

**Comment by cloudnull** [comment] 2016-10-11 23:40
The router hosting agent seems to have been scheduled to more than 1 l3 agent. 

``` console
# router on more than 1 l3 agent
# neutron l3-agent-list-hosting-router defaa18e-bbd6-4930-b990-c5168f81a943
+--------------------------------------+----------------------------------------------------+----------------+-------+----------+
| id                                   | host                                               | admin_state_up | alive | ha_state |
+--------------------------------------+----------------------------------------------------+----------------+-------+----------+
| 7b168f5f-ace0-4c94-b8e4-04dd7e58727a | 725155-network03-neutron-agents-container-fd4dcba5 | True           | :-)   |          |
| a8610a4d-b7ad-487d-9cc3-f4f98c9aa6a7 | 727112-network02-neutron-agents-container-cf16a000 | True           | :-)   |          |
+--------------------------------------+----------------------------------------------------+----------------+-------+----------+
```

I removed the extra agent and since then we've not been able to reproduce the issue.

``` shell
# test script
X=1
while [[ "$X" == 1 ]]; do
  echo '====================== START ======================'
  let COUNTER=COUNTER+1
  echo "RUNNING JOB $COUNTER"
  GIT_TRACE=1 git clone -vvv https://github.com/puppetlabs/puppetlabs-apache || X=0
  rm -rf puppetlabs-apache
  echo '====================== STOP ======================'
done
```

**Comment by dmsimard** [comment] 2016-10-13 13:26
@cloudnull I originally reported the issue and I'm happy to say it hasn't reproduced in a while.
It'd probably be fair to close this but I'll leave that up to you :)

**Comment by cloudnull** [comment] 2016-10-13 17:43
@dmsimard that's great to hear. @IRTermite please close when possible.

**Comment by mrhillsman** [comment] 2016-11-24 00:29
Close requested some time ago. Doing so now; can be re-opened if required.

**Closed as completed by mrhillsman** 2016-11-24 00:29 UTC
Labels: issue
